// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyRazorPagesApp.Models;

public class Answer
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Content is required.")]
    [StringLength(1000, ErrorMessage = "Content cannot be longer than 1000 characters.")]
    public required string Content { get; set; }

    public string UserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public   int PostId { get; set; }

    public virtual Post Post { get; set; }

    public int? DownVote { get; set; }
    public int? UpVote { get; set; }
    //public virtual ICollection<Vote> Votes { get; set; }
}