// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection.Metadata.Ecma335;

namespace MyRazorPagesApp.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public int? PostId { get; set; }

    public string? UserId { get; set; }
    
    [Required(ErrorMessage = "Content is required.")]
    [StringLength(200, ErrorMessage = "Content cannot be longer than 200 characters.")]
    public string? Content { get; set; }

    public DateTime? CommentTime { get; set; }

    public int? DownVote { get; set; }
    public int? UpVote { get; set; }
    public virtual ICollection<Vote> Votes { get; set; }


}