// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MyRazorPagesApp.Models;

public partial class Follower
{
    public string FollowerId { get; set; } = null!;

    public string FollowedId { get; set; } = null!;

    
}