// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyRazorPagesApp.Models;



public partial class Post
{
    
    /// Gets or sets the ID of the post.
    public int Id { get; set; }
    
    public string? Title { get; set; }
    
    [Required(ErrorMessage = "Content is required.")]
    [StringLength(300, ErrorMessage = "Content cannot be longer than 300 characters.")]
    public string Content { get; set; }

    public string? PostType { get; set; } //Question
    public int? ParentPostId { get; set; }
    public string? UserId { get; set; }
    public int? CommunityId { get; set; }
    public DateTime? CreatedDate { get; set; }
    public string? PostPictureUrl { get; set; }
    //public virtual ICollection<View> Views { get; set; } = new List<View>();
    //public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
    //public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();
    //public virtual ICollection<PostTopic> PostTopics { get; set; } = new List<PostTopic>();
    public int? Upvotes { get; set; }
    public int? Downvotes { get; set; }
    //public virtual ICollection<Vote> Votes { get; set; }
}