// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyRazorPagesApp.Models;

public class Topic
{
    public int TopicID { get; set; }
    public string TopicName { get; set; }
    public ICollection<PostTopic> PostTopics { get; set; }
}

