// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MyRazorPagesApp.Models;

public partial class UserProfile
{
    public int Id { get; set; }

    public string? UserId { get; set; }

    public string? Bio { get; set; }
   
    public string? ProfilePictureUrl { get; set; }

    public DateTime? AccountCreatedDate { get; set; }
}